default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: altea_api_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: altea_api_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  primary:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>